
ifeq ($(CONFIG_ARCH_SCX35), y)
ifeq ($(CONFIG_MACH_COREPRIMEVE3G),y)
obj-$(CONFIG_SPRD_VSP) += sprd_vsp_sc8830_coreprimeve3g.o
else
obj-$(CONFIG_SPRD_VSP) += sprd_vsp_sc8830.o
endif
else
obj-$(CONFIG_SPRD_VSP) += sprd_vsp_sc8825.o
endif
